### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by Ursusmaritimus07**
-Java 8 (http://weka.8497.n7.nabble.com/Error-when-installing-wekaDeeplearning4jCPU-td39037.html )

### CODE REVIEW

**Comment by Ursusmaritimus07** [comment]
the error is still present, it is very tiresome to find hidden requirements. it is best just to let the world know.
having said that, I truly appreciate what you do!
regards,
Alex

**Comment by steven-lang** [comment]
Which version of wekaDeeplearning4j are you using? The issue described in the thread you have linked is quite old and since then a lot has changed.

**Comment by Ursusmaritimus07** [comment]
Hi Steven:

Before I say anything else:

I'm using (clean install):

Ubuntu 16.04

Java JDK 8

Cuda 9.0 (with the 4 patches)

cuDNN 7.0.5

Anaconda

Python 3.6

Weka 3.8.3

I'm not a software engineer.


I was trying to use wekaDeeplearning4j-GPU-linux (1.4.0 ) but I just tested it an it doesn't work either.

I was trying to use that, one as wekaDeeplearning4j (1.5.6) doesn't work, I get the error attached.


From your webpage it gives the impression that it is easy, and any OS/Cuda/cuDNN/Java combination will work.

But what I'm finding is very different.


I really wish you would say:

For the easiest install use:

Ubuntu 16.04

Cuda 9.2 with cuDNN7.2

and Java 8

make use you install Weka3.8.3 and and use the package manager for the DL4j package.

install that and you won't need a PHD in Weka, and other in Cuda, etc.


to be honest, it 's been a very frustrating experience.

But I'm  trying to keep it positive and help, if I can , other people (That is why I suggested the changes in git)


Sorry, you question was short and I commented too much.

Any help is more than welcome!


Best regards,

Alex





________________________________

**Comment by steven-lang** [comment]
Hi Alex, first off, thanks for your suggestions.

> I really wish you would say:
>For the easiest install use:
>Ubuntu 16.04
>Cuda 9.2 with cuDNN7.2
>and Java 8
>make use you install Weka3.8.3 and and use the package manager for the DL4j package.

We specifically do not want to limit users to _one_ specific operating system-, Cuda/cuDNN-, Java- and Weka-version. This is to be as flexible as possible. Therefore, we list certain minimum dependencies that are required to use the package -- which you have already found in the `install.md` file. 

> I was trying to use that, one as wekaDeeplearning4j (1.5.6) doesn't work, I get the error attached.

Could you please describe further what exact problem/error you have? (There is no attachment)

**Comment by Ursusmaritimus07** [comment]
Hi Steven:

(spoiler alert, it worked)


Thanks for your reply.

Looks like the email filter took out the file.

I'll attach it again, but I will use a png format.


The reason I'm using this os, Cuda, cuDNN is that I also want to run Tensoflow with Keras...


Steven... I did everything again to take screen shots for you... but this time IT WORKED!  😊

I really don't know what to say.

I used the package manager, I didn't get the java error (It had failed 3 times before), but this time it worked.

the only difference, I uploaded other package first, to make sure the system was working, and if DL4J failed it was for sure the DL4J package to blame.

but this time it worked.

So I'm truly happy!

And I really appreciate your support!


Thanks again,


Alex.



________________________________

**Comment by steven-lang** [comment]
Hi Alex,

I'm happy to hear that. If you have any further problems/questions, feel free to create an issue in this GitHub repository.

Have fun!

**Pull request merged**
